import * as React from "react"
import type {HeadFC, PageProps} from "gatsby"
import Abstract from "../components/Abstract"
import Affiliation from "../components/Affiliation";
import Author from "../components/Author";
import CarouselComponent from "../components/Carousel";
import Citation from "../components/Citation";
import Footer from "../components/Footer";
import Heading from "../components/Heading";
import LinkGroup from "../components/LinkGroup";
import Thanks from "../components/Thanks"
import Title from "../components/Title"



const Article: React.FC = ({children}) => {
    return (
        <div
            className="mx-auto w-full max-w-[90%]
                       lg:max-w-4xl">
            {children}
        </div>
    )
}


export const Head: HeadFC = () => <title>PlaySlot: Controllable Object-Centric Video Prediction</title>

const IndexPage: React.FC<PageProps> = () => {
    return (
        <div>
            <main className="">
                <Article>
                    {/* Title */}
                    <Title>
                      PlaySlot: Learning Inverse Latent Dynamics for Controllable Object-Centric Video Prediction and Planning
                    </Title>

                    {/* Authors */}
                    <div className="flex flex-wrap justify-center text-lg mb-2.5 mt-0 leading-none">
                        <Author website={"http://angelvillarcorrales.com/templates/home.php"} firstAuthor={false} affiliations={""}>Angel Villar-Corrales</Author>
                        <Author website={"https://www.ais.uni-bonn.de/behnke/"} firstAuthor={false} affiliations={""}>Sven Behnke</Author>
                    </div>

                    {/* <Thanks>* Indicates equal contribution</Thanks> */}

                    {/* Affiliations */}
                    <div className="flex flex-wrap justify-center text-base mb-4 mt-0 leading-none">
                        <Affiliation website={"https://www.ais.uni-bonn.de/index.html"} number={""}>Autonomous Intelligent Systems, University of Bonn</Affiliation>
                    </div>

                    {/* Links */}
                    <LinkGroup arxivUrl={""} pdfUrl={""} otherUrls={
                        [
                            ["/bibtex.txt", "BibTex"],
                            ["https://github.com/angelvillar96/PlaySlot", "Code"],
                        ]}
                    />

                    {/* Abstract */}
                    <Abstract>
                      Predicting future scene representations is a crucial task for enabling robots to understand and interact with the environment. However, most existing methods rely on video sequences and
                      simulations with precise action annotations, limiting their ability to leverage the large amount
                      of available unlabeled video data. To address this challenge, we propose PlaySlot, an object-centric video prediction model that infers object representations and latent actions from unlabeled video sequences. It then uses these representations to forecast future object states and video frames. PlaySlot allows to generate multiple possible futures conditioned on latent actions, which can be inferred from video dynamics, provided by a user, or generated by a learned action policy, thus enabling versatile and interpretable world modeling. Our results show that PlaySlot outperforms both stochastic and object-centric baselines for video prediction across different environments. Furthermore, we show that our inferred latent actions can be used to learn robot behaviors sample-efficiently from unlabeled video demonstrations.
                    </Abstract>


                    <Heading>PlaySlot Training and Inference</Heading>
                    <div>
                      Overview of PlaySlot training and inference processes. <br></br>
                      <b> a) Training: </b> PlaySlot is trained given unlabeled video sequences by inferring object representations and latent actions, and using these representations to autoregressively forecast future video frames and object states. <br></br>
                      <b> b) Inference: </b> PlaySlot autoregressively forecasts future frames conditioned on a single frame and latent actions, which can be inferred from observations, provided by a user, or output by a learned action policy.
                    </div>
                    <br></br>


                    <img src="imgs/img_comb.png" alt="train_inference"></img>



                    <Heading> PlaySlots Predictions </Heading>

                    {/* RobotDB GIFs */}
                    <div>
                      <br></br>
                      <a class="subtitle">BlockPush</a>
                    </div>

                    <div class="gif-container">
                        <div class="gif-item">
                          <div class="gif-title">GT</div>
                          <img src="GIFs/seq_00/gt_GIF_frames.gif" alt="GT 00"></img>
                        </div>
                        <div class="gif-item">
                          <div class="gif-title">Pred</div>
                          <img src="GIFs/seq_00/pred_GIF_frames.gif" alt="Pred 00"></img>
                        </div>
                        <div class="gif-item">
                          <div class="gif-title">Slot Masks</div>
                        <img src="GIFs/seq_00/masks_GIF_masks.gif" alt="Segm 00"></img>
                      </div>
                      <div class="gif-item">
                        <div class="gif-title">Obj. 1</div>
                        <img src="GIFs/seq_00/gt_obj_1.gif" alt="Obj1 00"></img>
                      </div>
                      <div class="gif-item">
                        <div class="gif-title">Obj. 2</div>
                        <img src="GIFs/seq_00/gt_obj_2.gif" alt="Obj1 01"></img>
                      </div>
                      <div class="gif-item">
                        <div class="gif-title">Obj. 3</div>
                        <img src="GIFs/seq_00/gt_obj_5.gif" alt="Obj1 02"></img>
                      </div>
                      <div class="gif-item">
                        <div class="gif-title">Obj. 4</div>
                        <img src="GIFs/seq_00/gt_obj_7.gif" alt="Obj1 03"></img>
                      </div>
                    </div>

                    <div class="gif-container">
                      <div class="gif-item">
                        <img src="GIFs/seq_01/gt_GIF_frames.gif" alt="GT 00"></img>
                      </div>
                      <div class="gif-item">
                        <img src="GIFs/seq_01/pred_GIF_frames.gif" alt="Pred 00"></img>
                      </div>
                      <div class="gif-item">
                        <img src="GIFs/seq_01/masks_GIF_masks.gif" alt="Segm 00"></img>
                      </div>
                      <div class="gif-item">
                        <img src="GIFs/seq_01/gt_obj_1.gif" alt="Obj1 00"></img>
                      </div>
                      <div class="gif-item">
                        <img src="GIFs/seq_01/gt_obj_4.gif" alt="Obj1 01"></img>
                      </div>
                      <div class="gif-item">
                        <img src="GIFs/seq_01/gt_obj_7.gif" alt="Obj1 02"></img>
                      </div>
                      <div class="gif-item">
                        <img src="GIFs/seq_01/gt_obj_8.gif" alt="Obj1 03"></img>
                      </div>
                    </div>

                    <div class="gif-container">
                      <div class="gif-item">
                        <img src="GIFs/seq_02/gt_GIF_frames.gif" alt="GT 00"></img>
                      </div>
                      <div class="gif-item">
                        <img src="GIFs/seq_02/pred_GIF_frames.gif" alt="Pred 00"></img>
                      </div>
                      <div class="gif-item">
                        <img src="GIFs/seq_02/masks_GIF_masks.gif" alt="Segm 00"></img>
                      </div>
                      <div class="gif-item">
                        <img src="GIFs/seq_02/gt_obj_1.gif" alt="Obj1 00"></img>
                      </div>
                      <div class="gif-item">
                        <img src="GIFs/seq_02/gt_obj_3.gif" alt="Obj1 01"></img>
                      </div>
                      <div class="gif-item">
                        <img src="GIFs/seq_02/gt_obj_7.gif" alt="Obj1 02"></img>
                      </div>
                      <div class="gif-item">
                        <img src="GIFs/seq_02/gt_obj_8.gif" alt="Obj1 03"></img>
                      </div>
                    </div>


                    {/* METAWORLD GIFs */}

                    <br></br>
                    <div>
                      <br></br>
                      <a class="subtitle">MetaWorld Button-Press</a>
                    </div>

                    <div class="gif-container">
                      <div class="gif-item">
                        <img src="GIFs/seq_06/gt_GIF_frames.gif" alt="GT 00"></img>
                      </div>
                      <div class="gif-item">
                        <img src="GIFs/seq_06/pred_GIF_frames.gif" alt="Pred 00"></img>
                      </div>
                      <div class="gif-item">
                        <img src="GIFs/seq_06/masks_GIF_masks.gif" alt="Segm 00"></img>
                      </div>
                      <div class="gif-item">
                        <img src="GIFs/seq_06/gt_obj_1.gif" alt="Obj1 00"></img>
                      </div>
                      <div class="gif-item">
                        <img src="GIFs/seq_06/gt_obj_2.gif" alt="Obj1 01"></img>
                      </div>
                      <div class="gif-item">
                        <img src="GIFs/seq_06/gt_obj_3.gif" alt="Obj1 02"></img>
                      </div>
                      <div class="gif-item">
                        <img src="GIFs/seq_06/gt_obj_4.gif" alt="Obj1 03"></img>
                      </div>
                    </div>

                    <div class="gif-container">
                      <div class="gif-item">
                        <img src="GIFs/seq_07/gt_GIF_frames.gif" alt="GT 00"></img>
                      </div>
                      <div class="gif-item">
                        <img src="GIFs/seq_07/pred_GIF_frames.gif" alt="Pred 00"></img>
                      </div>
                      <div class="gif-item">
                        <img src="GIFs/seq_07/masks_GIF_masks.gif" alt="Segm 00"></img>
                      </div>
                      <div class="gif-item">
                        <img src="GIFs/seq_07/gt_obj_1.gif" alt="Obj1 00"></img>
                      </div>
                      <div class="gif-item">
                        <img src="GIFs/seq_07/gt_obj_2.gif" alt="Obj1 01"></img>
                      </div>
                      <div class="gif-item">
                        <img src="GIFs/seq_07/gt_obj_3.gif" alt="Obj1 02"></img>
                      </div>
                      <div class="gif-item">
                        <img src="GIFs/seq_07/gt_obj_4.gif" alt="Obj1 03"></img>
                      </div>
                    </div>

                    <div class="gif-container">
                      <div class="gif-item">
                        <img src="GIFs/seq_08/gt_GIF_frames.gif" alt="GT 00"></img>
                      </div>
                      <div class="gif-item">
                        <img src="GIFs/seq_08/pred_GIF_frames.gif" alt="Pred 00"></img>
                      </div>
                      <div class="gif-item">
                        <img src="GIFs/seq_08/masks_GIF_masks.gif" alt="Segm 00"></img>
                      </div>
                      <div class="gif-item">
                        <img src="GIFs/seq_08/gt_obj_1.gif" alt="Obj1 00"></img>
                      </div>
                      <div class="gif-item">
                        <img src="GIFs/seq_08/gt_obj_2.gif" alt="Obj1 01"></img>
                      </div>
                      <div class="gif-item">
                        <img src="GIFs/seq_08/gt_obj_3.gif" alt="Obj1 02"></img>
                      </div>
                      <div class="gif-item">
                        <img src="GIFs/seq_08/gt_obj_4.gif" alt="Obj1 03"></img>
                      </div>
                    </div>



                    {/* SKETCHY GIFs */}
                    <br></br>
                    <div>
                      <br></br>
                      <a class="subtitle">Sketchy</a>
                    </div>


                    <div class="gif-container">
                      <div class="gif-item">
                        <img src="GIFs/seq_03/gt_GIF_frames.gif" alt="GT 00"></img>
                      </div>
                      <div class="gif-item">
                        <img src="GIFs/seq_03/pred_GIF_frames.gif" alt="Pred 00"></img>
                      </div>
                      <div class="gif-item">
                        <img src="GIFs/seq_03/masks_GIF_masks.gif" alt="Segm 00"></img>
                      </div>
                      <div class="gif-item">
                        <img src="GIFs/seq_03/gt_obj_1.gif" alt="Obj1 00"></img>
                      </div>
                      <div class="gif-item">
                        <img src="GIFs/seq_03/gt_obj_5.gif" alt="Obj1 01"></img>
                      </div>
                      <div class="gif-item">
                        <img src="GIFs/seq_03/gt_obj_6.gif" alt="Obj1 02"></img>
                      </div>
                      <div class="gif-item">
                        <img src="GIFs/seq_03/gt_obj_7.gif" alt="Obj1 03"></img>
                      </div>
                    </div>

                    <div class="gif-container">
                      <div class="gif-item">
                        <img src="GIFs/seq_04/gt_GIF_frames.gif" alt="GT 00"></img>
                      </div>
                      <div class="gif-item">
                        <img src="GIFs/seq_04/pred_GIF_frames.gif" alt="Pred 00"></img>
                      </div>
                      <div class="gif-item">
                        <img src="GIFs/seq_04/masks_GIF_masks.gif" alt="Segm 00"></img>
                      </div>
                      <div class="gif-item">
                        <img src="GIFs/seq_04/gt_obj_5.gif" alt="Obj1 00"></img>
                      </div>
                      <div class="gif-item">
                        <img src="GIFs/seq_04/gt_obj_6.gif" alt="Obj1 01"></img>
                      </div>
                      <div class="gif-item">
                        <img src="GIFs/seq_04/gt_obj_7.gif" alt="Obj1 02"></img>
                      </div>
                      <div class="gif-item">
                        <img src="GIFs/seq_04/gt_obj_8.gif" alt="Obj1 03"></img>
                      </div>
                    </div>

                    <div class="gif-container">
                      <div class="gif-item">
                        <img src="GIFs/seq_05/gt_GIF_frames.gif" alt="GT 00"></img>
                      </div>
                      <div class="gif-item">
                        <img src="GIFs/seq_05/pred_GIF_frames.gif" alt="Pred 00"></img>
                      </div>
                      <div class="gif-item">
                        <img src="GIFs/seq_05/masks_GIF_masks.gif" alt="Segm 00"></img>
                      </div>
                      <div class="gif-item">
                        <img src="GIFs/seq_05/gt_obj_3.gif" alt="Obj1 00"></img>
                      </div>
                      <div class="gif-item">
                        <img src="GIFs/seq_05/gt_obj_5.gif" alt="Obj1 01"></img>
                      </div>
                      <div class="gif-item">
                        <img src="GIFs/seq_05/gt_obj_6.gif" alt="Obj1 02"></img>
                      </div>
                      <div class="gif-item">
                        <img src="GIFs/seq_05/gt_obj_8.gif" alt="Obj1 03"></img>
                      </div>
                    </div>


                    <Heading> Benchmarking </Heading>

                    <div>
                      PlaySlot achieves the best results in datasets that require modeling object interactions (BlockPush) or feature multiple moving objects (GridShapes), while maintaining competitive
                      performance on ButtonPress.
                    </div>
                    <br></br>

                    <img src="imgs/benchmark.png" alt="benchmark"></img>
                    <br></br>

                    <div>
                      Our proposed PlaySlot model accurately predicts the scene dynamics, even in the presence of occlusions and interactions between the robot and the objects; whereas the baselines (SVG and CADDY) fail to model object interactions, leading to blurriness or disappearing objects.
                    </div>

                    <div class="image-container">
                        <img src="imgs/qual_01.png" alt="qual_01"></img>
                        <img src="imgs/qual_02.png" alt="qual_02"></img>
                    </div>



                    <Heading> Learned Actions </Heading>

                    <div>
                      We visualize the video frames generated by PlaySlot be repeatedly conditioning the prediction
                      process on a single action prototype.
                    </div>


                    {/* RobotDB GIFs */}
                    <div>
                      <br></br>
                      <a class="subtitle">BlockPush</a>
                    </div>

                    <div class="gif-container">
                        <div class="gif-item">
                          <div class="gif-title">InvDyn</div>
                          <img src="GIFs/LearnedActions/RobotDB_00/inferred_dynamics.gif" alt="InvDym"></img>
                        </div>
                        <div class="gif-item">
                          <div class="gif-title">Act. 1</div>
                          <img src="GIFs/LearnedActions/RobotDB_00/action_proto_1.gif" alt="Act 0"></img>
                        </div>
                        <div class="gif-item">
                          <div class="gif-title">Act. 2</div>
                          <img src="GIFs/LearnedActions/RobotDB_00/action_proto_2.gif" alt="Act 1"></img>
                      </div>
                      <div class="gif-item">
                        <div class="gif-title">Act. 3</div>
                        <img src="GIFs/LearnedActions/RobotDB_00/action_proto_3.gif" alt="Act 2"></img>
                      </div>
                      <div class="gif-item">
                        <div class="gif-title">Act. 4</div>
                        <img src="GIFs/LearnedActions/RobotDB_00/action_proto_4.gif" alt="Act 3"></img>
                      </div>
                      <div class="gif-item">
                        <div class="gif-title">Act. 5</div>
                        <img src="GIFs/LearnedActions/RobotDB_00/action_proto_5.gif" alt="Act 4"></img>
                      </div>
                      <div class="gif-item">
                        <div class="gif-title">Act. 6</div>
                        <img src="GIFs/LearnedActions/RobotDB_00/action_proto_6.gif" alt="Act 5"></img>
                      </div>
                      <div class="gif-item">
                        <div class="gif-title">Act. 7</div>
                        <img src="GIFs/LearnedActions/RobotDB_00/action_proto_7.gif" alt="Act 6"></img>
                      </div>
                    </div>
                    <div class="gif-container">
                        <div class="gif-item">
                          {/* <div class="gif-title">InvDyn</div> */}
                          <img src="GIFs/LearnedActions/RobotDB_01/inferred_dynamics.gif" alt="InvDym"></img>
                        </div>
                        <div class="gif-item">
                          {/* <div class="gif-title">Act. 1</div> */}
                          <img src="GIFs/LearnedActions/RobotDB_01/action_proto_1.gif" alt="Act 0"></img>
                        </div>
                        <div class="gif-item">
                            {/* <div class="gif-title">Act. 2</div> */}
                            <img src="GIFs/LearnedActions/RobotDB_01/action_proto_2.gif" alt="Act 1"></img>
                        </div>
                        <div class="gif-item">
                          {/* <div class="gif-title">Act. 3</div> */}
                          <img src="GIFs/LearnedActions/RobotDB_01/action_proto_3.gif" alt="Act 2"></img>
                        </div>
                        <div class="gif-item">
                          {/* <div class="gif-title">Act. 4</div> */}
                          <img src="GIFs/LearnedActions/RobotDB_01/action_proto_4.gif" alt="Act 3"></img>
                        </div>
                        <div class="gif-item">
                          {/* <div class="gif-title">Act. 5</div> */}
                          <img src="GIFs/LearnedActions/RobotDB_01/action_proto_5.gif" alt="Act 4"></img>
                        </div>
                        <div class="gif-item">
                          {/* <div class="gif-title">Act. 6</div> */}
                          <img src="GIFs/LearnedActions/RobotDB_01/action_proto_6.gif" alt="Act 5"></img>
                        </div>
                        <div class="gif-item">
                          {/* <div class="gif-title">Act. 7</div> */}
                          <img src="GIFs/LearnedActions/RobotDB_01/action_proto_7.gif" alt="Act 6"></img>
                        </div>
                      </div>


                    {/* Metaworld GIFs */}
                    <div>
                      <br></br>
                      <a class="subtitle">MetaWorld: Button-Press</a>
                    </div>

                    <div class="gif-container">
                        <div class="gif-item">
                          <div class="gif-title">InvDyn</div>
                          <img src="GIFs/LearnedActions/ButtonPress_00/inferred_dynamics.gif" alt="InvDym"></img>
                        </div>
                        <div class="gif-item">
                          <div class="gif-title">Act. 1</div>
                          <img src="GIFs/LearnedActions/ButtonPress_00/action_proto_1.gif" alt="Act 0"></img>
                        </div>
                        <div class="gif-item">
                          <div class="gif-title">Act. 2</div>
                          <img src="GIFs/LearnedActions/ButtonPress_00/action_proto_2.gif" alt="Act 1"></img>
                      </div>
                      <div class="gif-item">
                        <div class="gif-title">Act. 3</div>
                        <img src="GIFs/LearnedActions/ButtonPress_00/action_proto_3.gif" alt="Act 2"></img>
                      </div>
                      <div class="gif-item">
                        <div class="gif-title">Act. 4</div>
                        <img src="GIFs/LearnedActions/ButtonPress_00/action_proto_4.gif" alt="Act 3"></img>
                      </div>
                      <div class="gif-item">
                        <div class="gif-title">Act. 5</div>
                        <img src="GIFs/LearnedActions/ButtonPress_00/action_proto_5.gif" alt="Act 4"></img>
                      </div>
                      <div class="gif-item">
                        <div class="gif-title">Act. 6</div>
                        <img src="GIFs/LearnedActions/ButtonPress_00/action_proto_6.gif" alt="Act 5"></img>
                      </div>
                      <div class="gif-item">
                        <div class="gif-title">Act. 7</div>
                        <img src="GIFs/LearnedActions/ButtonPress_00/action_proto_7.gif" alt="Act 6"></img>
                      </div>
                    </div>
                    <div class="gif-container">
                        <div class="gif-item">
                          {/* <div class="gif-title">InvDyn</div> */}
                          <img src="GIFs/LearnedActions/ButtonPress_01/inferred_dynamics.gif" alt="InvDym"></img>
                        </div>
                        <div class="gif-item">
                          {/* <div class="gif-title">Act. 1</div> */}
                          <img src="GIFs/LearnedActions/ButtonPress_01/action_proto_1.gif" alt="Act 0"></img>
                        </div>
                        <div class="gif-item">
                            {/* <div class="gif-title">Act. 2</div> */}
                            <img src="GIFs/LearnedActions/ButtonPress_01/action_proto_2.gif" alt="Act 1"></img>
                        </div>
                        <div class="gif-item">
                          {/* <div class="gif-title">Act. 3</div> */}
                          <img src="GIFs/LearnedActions/ButtonPress_01/action_proto_3.gif" alt="Act 2"></img>
                        </div>
                        <div class="gif-item">
                          {/* <div class="gif-title">Act. 4</div> */}
                          <img src="GIFs/LearnedActions/ButtonPress_01/action_proto_4.gif" alt="Act 3"></img>
                        </div>
                        <div class="gif-item">
                          {/* <div class="gif-title">Act. 5</div> */}
                          <img src="GIFs/LearnedActions/ButtonPress_01/action_proto_5.gif" alt="Act 4"></img>
                        </div>
                        <div class="gif-item">
                          {/* <div class="gif-title">Act. 6</div> */}
                          <img src="GIFs/LearnedActions/ButtonPress_01/action_proto_6.gif" alt="Act 5"></img>
                        </div>
                        <div class="gif-item">
                          {/* <div class="gif-title">Act. 7</div> */}
                          <img src="GIFs/LearnedActions/ButtonPress_01/action_proto_7.gif" alt="Act 6"></img>
                        </div>
                      </div>


                    {/* GridShapes */}
                    <div>
                      <br></br>
                      <a class="subtitle">GridShapes</a>
                    </div>


                    <div class="gif-container">
                        <div class="gif-item">
                          <div class="gif-title">InvDyn</div>
                          <img src="GIFs/LearnedActions/GridShapes_00/inferred_dynamics.gif" alt="InvDym"></img>
                        </div>
                        <div class="gif-item">
                          <div class="gif-title">Act. 1</div>
                          <img src="GIFs/LearnedActions/GridShapes_00/action_proto_1.gif" alt="Act 0"></img>
                        </div>
                        <div class="gif-item">
                          <div class="gif-title">Act. 2</div>
                          <img src="GIFs/LearnedActions/GridShapes_00/action_proto_2.gif" alt="Act 1"></img>
                      </div>
                      <div class="gif-item">
                        <div class="gif-title">Act. 3</div>
                        <img src="GIFs/LearnedActions/GridShapes_00/action_proto_3.gif" alt="Act 2"></img>
                      </div>
                      <div class="gif-item">
                        <div class="gif-title">Act. 4</div>
                        <img src="GIFs/LearnedActions/GridShapes_00/action_proto_4.gif" alt="Act 3"></img>
                      </div>
                      <div class="gif-item">
                        <div class="gif-title">Act. 5</div>
                        <img src="GIFs/LearnedActions/GridShapes_00/action_proto_5.gif" alt="Act 4"></img>
                      </div>
                    </div>
                    <div class="gif-container">
                        <div class="gif-item">
                          {/* <div class="gif-title">InvDyn</div> */}
                          <img src="GIFs/LearnedActions/GridShapes_01/inferred_dynamics.gif" alt="InvDym"></img>
                        </div>
                        <div class="gif-item">
                          {/* <div class="gif-title">Act. 1</div> */}
                          <img src="GIFs/LearnedActions/GridShapes_01/action_proto_1.gif" alt="Act 0"></img>
                        </div>
                        <div class="gif-item">
                            {/* <div class="gif-title">Act. 2</div> */}
                            <img src="GIFs/LearnedActions/GridShapes_01/action_proto_2.gif" alt="Act 1"></img>
                        </div>
                        <div class="gif-item">
                          {/* <div class="gif-title">Act. 3</div> */}
                          <img src="GIFs/LearnedActions/GridShapes_01/action_proto_3.gif" alt="Act 2"></img>
                        </div>
                        <div class="gif-item">
                          {/* <div class="gif-title">Act. 4</div> */}
                          <img src="GIFs/LearnedActions/GridShapes_01/action_proto_4.gif" alt="Act 3"></img>
                        </div>
                        <div class="gif-item">
                          {/* <div class="gif-title">Act. 5</div> */}
                          <img src="GIFs/LearnedActions/GridShapes_01/action_proto_5.gif" alt="Act 4"></img>
                        </div>
                      </div>


                    {/* Sketchy */}
                    <div>
                      <br></br>
                      <a class="subtitle">Sketchy</a>
                    </div>


                    <div class="gif-container">
                        <div class="gif-item">
                          <div class="gif-title">InvDyn</div>
                          <img src="GIFs/LearnedActions/Sketchy_00/inferred_dynamics.gif" alt="InvDym"></img>
                        </div>
                        <div class="gif-item">
                          <div class="gif-title">Act. 1</div>
                          <img src="GIFs/LearnedActions/Sketchy_00/action_proto_1.gif" alt="Act 0"></img>
                        </div>
                        <div class="gif-item">
                          <div class="gif-title">Act. 2</div>
                          <img src="GIFs/LearnedActions/Sketchy_00/action_proto_2.gif" alt="Act 1"></img>
                      </div>
                      <div class="gif-item">
                        <div class="gif-title">Act. 3</div>
                        <img src="GIFs/LearnedActions/Sketchy_00/action_proto_3.gif" alt="Act 2"></img>
                      </div>
                      <div class="gif-item">
                        <div class="gif-title">Act. 4</div>
                        <img src="GIFs/LearnedActions/Sketchy_00/action_proto_5.gif" alt="Act 3"></img>
                      </div>
                      <div class="gif-item">
                        <div class="gif-title">Act. 5</div>
                        <img src="GIFs/LearnedActions/Sketchy_00/action_proto_6.gif" alt="Act 4"></img>
                      </div>
                      <div class="gif-item">
                        <div class="gif-title">Act. 6</div>
                        <img src="GIFs/LearnedActions/Sketchy_00/action_proto_7.gif" alt="Act 7"></img>
                      </div>
                      <div class="gif-item">
                        <div class="gif-title">Act. 7</div>
                        <img src="GIFs/LearnedActions/Sketchy_00/action_proto_8.gif" alt="Act 6"></img>
                      </div>
                    </div>
                    <div class="gif-container">
                        <div class="gif-item">
                          {/* <div class="gif-title">InvDyn</div> */}
                          <img src="GIFs/LearnedActions/Sketchy_01/inferred_dynamics.gif" alt="InvDym"></img>
                        </div>
                        <div class="gif-item">
                          {/* <div class="gif-title">Act. 1</div> */}
                          <img src="GIFs/LearnedActions/Sketchy_01/action_proto_1.gif" alt="Act 0"></img>
                        </div>
                        <div class="gif-item">
                          {/* <div class="gif-title">Act. 2</div> */}
                          <img src="GIFs/LearnedActions/Sketchy_01/action_proto_2.gif" alt="Act 1"></img>
                      </div>
                      <div class="gif-item">
                        {/* <div class="gif-title">Act. 3</div> */}
                        <img src="GIFs/LearnedActions/Sketchy_01/action_proto_3.gif" alt="Act 2"></img>
                      </div>
                      <div class="gif-item">
                        {/* <div class="gif-title">Act. 4</div> */}
                        <img src="GIFs/LearnedActions/Sketchy_01/action_proto_5.gif" alt="Act 3"></img>
                      </div>
                      <div class="gif-item">
                        {/* <div class="gif-title">Act. 5</div> */}
                        <img src="GIFs/LearnedActions/Sketchy_01/action_proto_6.gif" alt="Act 4"></img>
                      </div>
                      <div class="gif-item">
                        {/* <div class="gif-title">Act. 6</div> */}
                        <img src="GIFs/LearnedActions/Sketchy_01/action_proto_7.gif" alt="Act 7"></img>
                      </div>
                      <div class="gif-item">
                        {/* <div class="gif-title">Act. 7</div> */}
                        <img src="GIFs/LearnedActions/Sketchy_01/action_proto_8.gif" alt="Act 6"></img>
                      </div>
                    </div>



                    <Heading> Learned Behaviors from Unlabelled Expert Demonstrations </Heading>

                    PlaySlot can learn robot behaviors from *unlabelled* expert demonstrations in a sample-efficent manner. Furthermore, we train a shallow model to map from PlaySlot's latent actions to the real action space, thus allowing to execute the learn behaviors.

                    In the GIFs below, we show predicted trajectories within PlaySlot’s latent imagination, where the model, starting from a single reference frame, autoregressively generates latent actions using the policy model and predicts future scene states in the latent space, as well as the simulated execution of the decoded latent actions in the corresponding environment.


                    {/* MetaWorld: Button-Press */}
                    <div>
                      <br></br>
                      <a class="subtitle">MetaWorld: Button-Press</a>
                    </div>

                    <div class="gif-container">
                        <div class="gif-item">
                          <div class="gif-title">Latent Predictions</div>
                          <img src="GIFs/Behaviors/ButtonPress_00/pred_GIF_frames.gif" alt="Pred"></img>
                        </div>
                        <div class="gif-item">
                          <div class="gif-title">Predicted Slot Masks</div>
                          <img src="GIFs/Behaviors/ButtonPress_00/masks_GIF_masks.gif" alt="Masks"></img>
                        </div>
                        <div class="gif-item">
                          <div class="gif-title">Simulated Execution</div>
                          <img src="GIFs/Behaviors/ButtonPress_00/sim_GIF_frames.gif" alt="Sim"></img>
                      </div>
                    </div>
                    <div class="gif-container">
                        <div class="gif-item">
                          {/* <div class="gif-title">Latent Predictions</div> */}
                          <img src="GIFs/Behaviors/ButtonPress_01/pred_GIF_frames.gif" alt="Pred"></img>
                        </div>
                        <div class="gif-item">
                          {/* <div class="gif-title">Predicted Slot Masks</div> */}
                          <img src="GIFs/Behaviors/ButtonPress_01/masks_GIF_masks.gif" alt="Masks"></img>
                        </div>
                        <div class="gif-item">
                          {/* <div class="gif-title">Simulated Execution</div> */}
                          <img src="GIFs/Behaviors/ButtonPress_01/sim_GIF_frames.gif" alt="Sim"></img>
                      </div>
                    </div>
                    <div class="gif-container">
                        <div class="gif-item">
                          {/* <div class="gif-title">Latent Predictions</div> */}
                          <img src="GIFs/Behaviors/ButtonPress_02/pred_GIF_frames.gif" alt="Pred"></img>
                        </div>
                        <div class="gif-item">
                          {/* <div class="gif-title">Predicted Slot Masks</div> */}
                          <img src="GIFs/Behaviors/ButtonPress_02/masks_GIF_masks.gif" alt="Masks"></img>
                        </div>
                        <div class="gif-item">
                          {/* <div class="gif-title">Simulated Execution</div> */}
                          <img src="GIFs/Behaviors/ButtonPress_02/sim_GIF_frames.gif" alt="Sim"></img>
                      </div>
                    </div>


                    {/* MetaWorld: Button-Press */}
                    <div>
                      <br></br>
                      <a class="subtitle">BlockPush</a>
                    </div>

                    <div class="gif-container">
                        <div class="gif-item">
                          <div class="gif-title">Latent Predictions</div>
                          <img src="GIFs/Behaviors/BlockPush_00/pred_GIF_frames.gif" alt="Pred"></img>
                        </div>
                        <div class="gif-item">
                          <div class="gif-title">Predicted Slot Masks</div>
                          <img src="GIFs/Behaviors/BlockPush_00/masks_GIF_masks.gif" alt="Masks"></img>
                        </div>
                        <div class="gif-item">
                          <div class="gif-title">Simulated Execution</div>
                          <img src="GIFs/Behaviors/BlockPush_00/sim_GIF_frames.gif" alt="Sim"></img>
                      </div>
                    </div>
                    <div class="gif-container">
                        <div class="gif-item">
                          {/* <div class="gif-title">Latent Predictions</div> */}
                          <img src="GIFs/Behaviors/BlockPush_01/pred_GIF_frames.gif" alt="Pred"></img>
                        </div>
                        <div class="gif-item">
                          {/* <div class="gif-title">Predicted Slot Masks</div> */}
                          <img src="GIFs/Behaviors/BlockPush_01/masks_GIF_masks.gif" alt="Masks"></img>
                        </div>
                        <div class="gif-item">
                          {/* <div class="gif-title">Simulated Execution</div> */}
                          <img src="GIFs/Behaviors/BlockPush_01/sim_GIF_frames.gif" alt="Sim"></img>
                      </div>
                    </div>
                    <div class="gif-container">
                        <div class="gif-item">
                          {/* <div class="gif-title">Latent Predictions</div> */}
                          <img src="GIFs/Behaviors/BlockPush_02/pred_GIF_frames.gif" alt="Pred"></img>
                        </div>
                        <div class="gif-item">
                          {/* <div class="gif-title">Predicted Slot Masks</div> */}
                          <img src="GIFs/Behaviors/BlockPush_02/masks_GIF_masks.gif" alt="Masks"></img>
                        </div>
                        <div class="gif-item">
                          {/* <div class="gif-title">Simulated Execution</div> */}
                          <img src="GIFs/Behaviors/BlockPush_02/sim_GIF_frames.gif" alt="Sim"></img>
                      </div>
                    </div>

                    <Citation/>


                    </Article>

                <Footer
                    githubUrl="https://github.com/angelvillar96"
                    googleScholarUrl="https://scholar.google.com/citations?user=NCUoKLMAAAAJ&hl=en"
                    linkedInUrl="http://angelvillarcorrales.com/templates/home.php"
                />
            </main>
        </div>
    );
};

export default IndexPage;
