import * as React from "react"
import type {HeadFC, PageProps} from "gatsby"
import Abstract from "../components/Abstract"
import Affiliation from "../components/Affiliation";
import Author from "../components/Author";
import CarouselComponent from "../components/Carousel";
import Citation from "../components/Citation";
import Footer from "../components/Footer";
import Heading from "../components/Heading";
import LinkGroup from "../components/LinkGroup";
import Thanks from "../components/Thanks"
import Title from "../components/Title"



const Article: React.FC = ({children}) => {
    return (
        <div
            className="mx-auto w-full max-w-[90%]
                       lg:max-w-4xl">
            {children}
        </div>
    )
}


export const Head: HeadFC = () => <title>Project Page Template</title>

const IndexPage: React.FC<PageProps> = () => {
    return (
        <div>
            <main className="">
                <Article>
                    {/* Title */}
                    <Title>
                      PlaySlot: Learning Inverse Latent Dynamics for Controllable Object-Centric Video Prediction and Planning
                    </Title>

                    {/* Authors */}
                    <div className="flex flex-wrap justify-center text-lg mb-2.5 mt-0 leading-none">
                        <Author website={"http://angelvillarcorrales.com/templates/home.php"} firstAuthor={false} affiliations={"1"}>Angel Villar-Corrales</Author>
                        <Author website={"https://www.ais.uni-bonn.de/behnke/"} firstAuthor={false} affiliations={"1"}>Sven Behnke</Author>
                    </div>

                    <Thanks>* Indicates equal contribution</Thanks>

                    {/* Affiliations */}
                    <div className="flex flex-wrap justify-center text-base mb-4 mt-0 leading-none">
                        <Affiliation website={""} number={"1"}>Autonomous Intelligent Systems, University of Bonn</Affiliation>
                    </div>

                    {/* Links */}
                    <LinkGroup arxivUrl={""} pdfUrl={""} otherUrls={
                        [
                            ["/bibtex.txt", "BibTex"],
                            ["https://github.com/angelvillar96/PlaySlot", "Code"],
                        ]}
                    />
                    {/* ["", "Video"] */}

                    {/* Abstract */}
                    <Abstract>
                      Predicting future scene representations is a crucial task for enabling robots to understand and interact with the environment. However, most existing methods rely on video sequences and
                      simulations with precise action annotations, limiting their ability to leverage the large amount
                      of available unlabeled video data. To address this challenge, we propose PlaySlot, an object-centric video prediction model that infers object representations and latent actions from unlabeled video sequences. It then uses these representations to forecast future object states and video frames. PlaySlot allows to generate multiple possible futures conditioned on latent actions, which can be inferred from video dynamics, provided by a user, or generated by a learned action policy, thus enabling versatile and interpretable world modeling. Our results show that PlaySlot outperforms both stochastic and object-centric baselines for video prediction across different environments. Furthermore, we show that our inferred latent actions can be used to learn robot behaviors sample-efficiently from unlabeled video demonstrations.
                    </Abstract>


                    <Heading>PlaySlot Training and Inference</Heading>
                    <div>
                      Overview of PlaySlot training and inference processes. <br></br>
                      <b> a) Training: </b> PlaySlot is trained given unlabeled video sequences by inferring object representations S and latent actions ẑ, and using these representations to autoregressively forecast future video frames and object states. <br></br>
                      <b> b) Inference: </b> PlaySlot autoregressively forecasts future frames conditioned on a single frame X1 and latent actions ẑ, which can be inferred from observations, provided by a user, or output by a learned action policy.
                    </div>
                    <br></br>


                    <img src="/imgs/img_comb.png" alt="train_inference"></img>



                    <Heading> PlaySlots Predictions </Heading>

                    {/* RobotDB GIFs */}
                    <div class="gif-container">
                        <div class="gif-item">
                          <div class="gif-title">GT</div>
                          <img src="/GIFs/seq_00/gt_GIF_frames.gif" alt="GT 00"></img>
                        </div>
                        <div class="gif-item">
                          <div class="gif-title">Pred</div>
                          <img src="/GIFs/seq_00/pred_GIF_frames.gif" alt="Pred 00"></img>
                        </div>
                        <div class="gif-item">
                          <div class="gif-title">Slot Masks</div>
                        <img src="/GIFs/seq_00/masks_GIF_masks.gif" alt="Segm 00"></img>
                      </div>
                      <div class="gif-item">
                        <div class="gif-title">Obj. 1</div>
                        <img src="/GIFs/seq_00/gt_obj_1.gif" alt="Obj1 00"></img>
                      </div>
                      <div class="gif-item">
                        <div class="gif-title">Obj. 2</div>
                        <img src="/GIFs/seq_00/gt_obj_2.gif" alt="Obj1 01"></img>
                      </div>
                      <div class="gif-item">
                        <div class="gif-title">Obj. 3</div>
                        <img src="/GIFs/seq_00/gt_obj_5.gif" alt="Obj1 02"></img>
                      </div>
                      <div class="gif-item">
                        <div class="gif-title">Obj. 4</div>
                        <img src="/GIFs/seq_00/gt_obj_7.gif" alt="Obj1 03"></img>
                      </div>
                    </div>

                    <div class="gif-container">
                      <div class="gif-item">
                        <img src="/GIFs/seq_01/gt_GIF_frames.gif" alt="GT 00"></img>
                      </div>
                      <div class="gif-item">
                        <img src="/GIFs/seq_01/pred_GIF_frames.gif" alt="Pred 00"></img>
                      </div>
                      <div class="gif-item">
                        <img src="/GIFs/seq_01/masks_GIF_masks.gif" alt="Segm 00"></img>
                      </div>
                      <div class="gif-item">
                        <img src="/GIFs/seq_01/gt_obj_1.gif" alt="Obj1 00"></img>
                      </div>
                      <div class="gif-item">
                        <img src="/GIFs/seq_01/gt_obj_4.gif" alt="Obj1 01"></img>
                      </div>
                      <div class="gif-item">
                        <img src="/GIFs/seq_01/gt_obj_7.gif" alt="Obj1 02"></img>
                      </div>
                      <div class="gif-item">
                        <img src="/GIFs/seq_01/gt_obj_8.gif" alt="Obj1 03"></img>
                      </div>
                    </div>

                    <div class="gif-container">
                      <div class="gif-item">
                        <img src="/GIFs/seq_02/gt_GIF_frames.gif" alt="GT 00"></img>
                      </div>
                      <div class="gif-item">
                        <img src="/GIFs/seq_02/pred_GIF_frames.gif" alt="Pred 00"></img>
                      </div>
                      <div class="gif-item">
                        <img src="/GIFs/seq_02/masks_GIF_masks.gif" alt="Segm 00"></img>
                      </div>
                      <div class="gif-item">
                        <img src="/GIFs/seq_02/gt_obj_1.gif" alt="Obj1 00"></img>
                      </div>
                      <div class="gif-item">
                        <img src="/GIFs/seq_02/gt_obj_3.gif" alt="Obj1 01"></img>
                      </div>
                      <div class="gif-item">
                        <img src="/GIFs/seq_02/gt_obj_7.gif" alt="Obj1 02"></img>
                      </div>
                      <div class="gif-item">
                        <img src="/GIFs/seq_02/gt_obj_8.gif" alt="Obj1 03"></img>
                      </div>
                    </div>


                    {/* METAWORLD GIFs */}
                    <br></br>
                    <div class="gif-container">
                      <div class="gif-item">
                        <img src="/GIFs/seq_06/gt_GIF_frames.gif" alt="GT 00"></img>
                      </div>
                      <div class="gif-item">
                        <img src="/GIFs/seq_06/pred_GIF_frames.gif" alt="Pred 00"></img>
                      </div>
                      <div class="gif-item">
                        <img src="/GIFs/seq_06/masks_GIF_masks.gif" alt="Segm 00"></img>
                      </div>
                      <div class="gif-item">
                        <img src="/GIFs/seq_06/gt_obj_1.gif" alt="Obj1 00"></img>
                      </div>
                      <div class="gif-item">
                        <img src="/GIFs/seq_06/gt_obj_2.gif" alt="Obj1 01"></img>
                      </div>
                      <div class="gif-item">
                        <img src="/GIFs/seq_06/gt_obj_3.gif" alt="Obj1 02"></img>
                      </div>
                      <div class="gif-item">
                        <img src="/GIFs/seq_06/gt_obj_4.gif" alt="Obj1 03"></img>
                      </div>
                    </div>

                    <div class="gif-container">
                      <div class="gif-item">
                        <img src="/GIFs/seq_07/gt_GIF_frames.gif" alt="GT 00"></img>
                      </div>
                      <div class="gif-item">
                        <img src="/GIFs/seq_07/pred_GIF_frames.gif" alt="Pred 00"></img>
                      </div>
                      <div class="gif-item">
                        <img src="/GIFs/seq_07/masks_GIF_masks.gif" alt="Segm 00"></img>
                      </div>
                      <div class="gif-item">
                        <img src="/GIFs/seq_07/gt_obj_1.gif" alt="Obj1 00"></img>
                      </div>
                      <div class="gif-item">
                        <img src="/GIFs/seq_07/gt_obj_2.gif" alt="Obj1 01"></img>
                      </div>
                      <div class="gif-item">
                        <img src="/GIFs/seq_07/gt_obj_3.gif" alt="Obj1 02"></img>
                      </div>
                      <div class="gif-item">
                        <img src="/GIFs/seq_07/gt_obj_4.gif" alt="Obj1 03"></img>
                      </div>
                    </div>

                    <div class="gif-container">
                      <div class="gif-item">
                        <img src="/GIFs/seq_08/gt_GIF_frames.gif" alt="GT 00"></img>
                      </div>
                      <div class="gif-item">
                        <img src="/GIFs/seq_08/pred_GIF_frames.gif" alt="Pred 00"></img>
                      </div>
                      <div class="gif-item">
                        <img src="/GIFs/seq_08/masks_GIF_masks.gif" alt="Segm 00"></img>
                      </div>
                      <div class="gif-item">
                        <img src="/GIFs/seq_08/gt_obj_1.gif" alt="Obj1 00"></img>
                      </div>
                      <div class="gif-item">
                        <img src="/GIFs/seq_08/gt_obj_2.gif" alt="Obj1 01"></img>
                      </div>
                      <div class="gif-item">
                        <img src="/GIFs/seq_08/gt_obj_3.gif" alt="Obj1 02"></img>
                      </div>
                      <div class="gif-item">
                        <img src="/GIFs/seq_08/gt_obj_4.gif" alt="Obj1 03"></img>
                      </div>
                    </div>



                    {/* SKETCHY GIFs */}
                    <br></br>
                    <div class="gif-container">
                      <div class="gif-item">
                        <img src="/GIFs/seq_03/gt_GIF_frames.gif" alt="GT 00"></img>
                      </div>
                      <div class="gif-item">
                        <img src="/GIFs/seq_03/pred_GIF_frames.gif" alt="Pred 00"></img>
                      </div>
                      <div class="gif-item">
                        <img src="/GIFs/seq_03/masks_GIF_masks.gif" alt="Segm 00"></img>
                      </div>
                      <div class="gif-item">
                        <img src="/GIFs/seq_03/gt_obj_1.gif" alt="Obj1 00"></img>
                      </div>
                      <div class="gif-item">
                        <img src="/GIFs/seq_03/gt_obj_5.gif" alt="Obj1 01"></img>
                      </div>
                      <div class="gif-item">
                        <img src="/GIFs/seq_03/gt_obj_6.gif" alt="Obj1 02"></img>
                      </div>
                      <div class="gif-item">
                        <img src="/GIFs/seq_03/gt_obj_7.gif" alt="Obj1 03"></img>
                      </div>
                    </div>

                    <div class="gif-container">
                      <div class="gif-item">
                        <img src="/GIFs/seq_04/gt_GIF_frames.gif" alt="GT 00"></img>
                      </div>
                      <div class="gif-item">
                        <img src="/GIFs/seq_04/pred_GIF_frames.gif" alt="Pred 00"></img>
                      </div>
                      <div class="gif-item">
                        <img src="/GIFs/seq_04/masks_GIF_masks.gif" alt="Segm 00"></img>
                      </div>
                      <div class="gif-item">
                        <img src="/GIFs/seq_04/gt_obj_5.gif" alt="Obj1 00"></img>
                      </div>
                      <div class="gif-item">
                        <img src="/GIFs/seq_04/gt_obj_6.gif" alt="Obj1 01"></img>
                      </div>
                      <div class="gif-item">
                        <img src="/GIFs/seq_04/gt_obj_7.gif" alt="Obj1 02"></img>
                      </div>
                      <div class="gif-item">
                        <img src="/GIFs/seq_04/gt_obj_8.gif" alt="Obj1 03"></img>
                      </div>
                    </div>

                    <div class="gif-container">
                      <div class="gif-item">
                        <img src="/GIFs/seq_05/gt_GIF_frames.gif" alt="GT 00"></img>
                      </div>
                      <div class="gif-item">
                        <img src="/GIFs/seq_05/pred_GIF_frames.gif" alt="Pred 00"></img>
                      </div>
                      <div class="gif-item">
                        <img src="/GIFs/seq_05/masks_GIF_masks.gif" alt="Segm 00"></img>
                      </div>
                      <div class="gif-item">
                        <img src="/GIFs/seq_05/gt_obj_3.gif" alt="Obj1 00"></img>
                      </div>
                      <div class="gif-item">
                        <img src="/GIFs/seq_05/gt_obj_5.gif" alt="Obj1 01"></img>
                      </div>
                      <div class="gif-item">
                        <img src="/GIFs/seq_05/gt_obj_6.gif" alt="Obj1 02"></img>
                      </div>
                      <div class="gif-item">
                        <img src="/GIFs/seq_05/gt_obj_8.gif" alt="Obj1 03"></img>
                      </div>
                    </div>


                    <Heading> Benchmarking </Heading>

                    <div>
                      PlaySlot achieves the best results in datasets that require modeling object interactions (BlockPush) or feature multiple moving objects (GridShapes), while maintaining competitive
                      performance on ButtonPress-
                    </div>
                    <br></br>

                    <img src="/imgs/benchmark.png" alt="benchmark"></img>
                    <br></br>

                    <div>
                      Our proposed PlaySlot model accurately predicts the scene dynamics, even in the presence of occlusions and interactions between the robot and the objects; whereas the baselines (SVG and CADDY) fail to model object interactions, leading to blurriness or disappearing objects.
                    </div>

                    <div class="image-container">
                        <img src="/imgs/qual_01.png" alt="qual_01"></img>
                        <img src="/imgs/qual_02.png" alt="qual_02"></img>
                    </div>



                    <Heading> Learned Actions </Heading>


                    <Heading> Learned Behaviors from Unlabelled Expert Demonstrations </Heading>



                    <Citation/>


                    </Article>

                <Footer
                    githubUrl="https://github.com/angelvillar96"
                    googleScholarUrl="https://scholar.google.com/citations?user=NCUoKLMAAAAJ&hl=en"
                    linkedInUrl="http://angelvillarcorrales.com/templates/home.php"
                />
            </main>
        </div>
    );
};

export default IndexPage;
